path: '/home/vinicius_lazzeri/Documents/detector-veiculos/dataset'
train: train/images
val: valid/images
test: test/images

nc: 12
names: ['big bus', 'big truck', 'bus-l-', 'bus-s-', 'car', 'mid truck', 'small bus', 'small truck', 'truck-l-', 'truck-m-', 'truck-s-', 'truck-xl-']

roboflow:
  workspace: roboflow-100
  project: vehicles-q0x2v
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/roboflow-100/vehicles-q0x2v/dataset/2